<?php

namespace BlogBundle\Repository;

use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
// :o :o te5dem but no need for it
//    public function findByCategorie($categorie)
//    {
//        $qb = $this->createQueryBuilder('s');
//        $qb->where('s.categorie = :categorie');
//        $qb->setParameter('categorie', $categorie);
//        return $qb->getQuery()->getResult();
//    }

    public function findArticleAuteurQB1($auteur)
    {
        $qb = $this->createQueryBuilder('s');
        $qb->where('s.auteur=:auteur')
            ->setParameter('auteur', '$auteur');
        return $qb->getQuery()->getResult();
    }

    public function rechercheSimple($chaine)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.titre like :chaine')
//            ->orderBy('u.id')
            ->setParameter('chaine', '$chaine');
        return $qb->getQuery()->getResult();
    }

//Recuperer dans le url :/
    public function exempleFindByAuteur($auteur)
    {
        $query = $this
            ->getEntityManager()
            ->createQuery('select m FROM BlogBundle:Article m where m.auteur=:auteur ')
            ->setParameter('auteur', $auteur);
        return $query->getResult();
    }

    public function exempleFindByAuteurav($motcle)
    {
        $query = $this->createQueryBuilder('article')
            ->where('article.titre like :titre')
            ->setParameter(':titre', '%' . '$motcle' . '%')
            ->orderBy('article.titre', 'desc')
            ->getQuery();
        return $query->getResult();
    }

    public function search($statut)
    {
        $query = $this->getEntityManager()->createQuery('SELECT C FROM BlogBundle:Article C WHERE C.titre like :stat');
        $query->setParameter(':stat', '%' . $statut . '%');
        return $query->getResult();
    }

    public function findIdDQL($id)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT m FROM BlogBundle:Article m 
        WHERE m.categorie LIKE :id ')
            ->setParameter('id', '%' . $id . '%')
            ->getResult();
    }


    public function findEntitiesByString($str)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a
                FROM BlogBundle:Article a
                WHERE a.titre LIKE :str'
            )
            ->setParameter('str', '%' . $str . '%')
            ->getResult();
    }

}
