<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function countUser()
    {
        $query = $this->getEntityManager()->createQuery('SELECT count(R.id) as nm from AppBundle:User R');
        return $query->getResult();
    }
}
