cv:
    resource: "@CvBundle/Resources/config/routing.yml"
    prefix:   /

fix:
    resource: "@FixBundle/Resources/config/routing.yml"
    prefix:   /

rec:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /freelancer

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"