<?php

namespace FixBundle\Repository;

/**
 * ApplayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplayRepository extends \Doctrine\ORM\EntityRepository
{
    public function updateEtat($id)
    {

        $query=$this->getEntityManager()
            ->createQuery("UPDATE FixBundle:applay m SET m.etat=1 where m.id='$id'");
        return $query->getResult();
    }
}
