<?php

namespace ForumBundle\Repository;

/**
 * articleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class articleRepository extends \Doctrine\ORM\EntityRepository
{
    public function orderdate()
    {
        $query  = $this->getEntityManager()->createQuery("SELECT C FROM ForumBundle:article C  ORDER BY C.date DESC")
            ;
        return $query->getResult();
    }
    public function count()
    {
        $query  = $this->getEntityManager()->createQuery('SELECT count(C.id) as nm FROM ForumBundle:article C');
        return $query->getResult();
    }

    public function orderlikes()
    {
       // $query1  = $this->getEntityManager()->createQuery('SELECT count(C.idclaim) as nm FROM ClaimBundle:Claim C');

        $query  = $this->getEntityManager()->createQuery("SELECT C FROM ForumBundle:like_q C  ORDER BY count(count) DESC")
        ;
        return $query->getResult();
    }
    public function search($titre)
    {
        $query  = $this->getEntityManager()->createQuery("SELECT C FROM ForumBundle:article C WHERE C.titre like '%stat%'");
        $query->setParameter('stat','%'.$titre.'%' );
        return $query->getResult();
    }
    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT g
                FROM ForumBundle:article g
                WHERE g.titre LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }
}
