jobposts_homepage:
    path:     jobposts_homepage/
    defaults: { _controller: JobpostsBundle:Default:index }


AjouterAnnonce:
    path:     AjouterAnnonce/
    defaults: { _controller: JobpostsBundle:Default:AjouterAnnonce }

Listeannonces:
    path:     Listeannonces/
    defaults: { _controller: JobpostsBundle:Default:Listeannonces }

SupprimerAnnonce:
    path:     SupprimerAnnonce/{id}
    defaults: { _controller: JobpostsBundle:Default:SupprimerAnnonce }

modifierAnnonce:
    path:     /modifierAnnonce/{id}
    defaults: { _controller: JobpostsBundle:Default:modifierAnnonce }

Listedemandes:
    path:     Listedemandes/
    defaults: { _controller: JobpostsBundle:Default:Listedemandes }

Approuverdemande:
    path:     Approuverdemande/{id}
    defaults: { _controller: JobpostsBundle:Default:Approuverdemande }

ListeAnnoncesdatatable:
    path:     ListeAnnoncesdatatable/
    defaults: { _controller: JobpostsBundle:Default:ListeAnnoncesdatatable }

JsonDemandes:
    path:     /JsonDemandes/
    defaults: { _controller: JobpostsBundle:Default:JsonDemandes }

calendar:
    path:     /calendar/
    defaults: { _controller: JobpostsBundle:Default:calendar }

