<?php

namespace ReclamationBundle\Repository;

/**
 * ReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseRepository extends \Doctrine\ORM\EntityRepository
{
    public function myResponse($id)
    {
        $query  = $this->getEntityManager()->createQuery("SELECT R FROM ReclamationBundle:Reponse R WHERE R.id= :id")
            ->setParameter(':id',$id);
        return $query->getResult();
    }
}
