<?php

namespace ReclamationBundle\Repository;

/**
 * ReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationRepository extends \Doctrine\ORM\EntityRepository
{

    public function myclaims($id)
    {
        $query  = $this->getEntityManager()->createQuery("SELECT C FROM ReclamationBundle:Reclamation C WHERE C.claimerId= :id")
            ->setParameter(':id',$id);
        return $query->getResult();
    }

    public function order($id)
    {
        $query  = $this->getEntityManager()->createQuery("SELECT C FROM ReclamationBundle:Reclamation C WHERE C.claimerId= :id ORDER BY C.date")
            ->setParameter(':id',$id);
        return $query->getResult();
    }

    public function orderTreated($id)
    {
        $query  = $this->getEntityManager()->createQuery("SELECT C FROM ReclamationBundle:Reclamation C WHERE C.claimerId= :id ORDER BY C.treated DESC")
            ->setParameter(':id',$id);
        return $query->getResult();
    }

    public function orderTreatedAdmin()
    {
        $query  = $this->getEntityManager()->createQuery("SELECT C FROM ReclamationBundle:Reclamation C ORDER BY C.treated ASC");
        return $query->getResult();
    }

    public function search($statut)
    {
        $query  = $this->getEntityManager()->createQuery('SELECT C FROM ReclamationBundle:Reclamation C WHERE C.statut like :stat');
        $query->setParameter(':stat','%'.$statut.'%' );
        return $query->getResult();
    }

    public function countClaims()
    {
        $query  = $this->getEntityManager()->createQuery('SELECT count(C.id) as nm FROM ReclamationBundle:Reclamation C');
        return $query->getResult();
    }

    public function countBug()
    {
        $query  = $this->getEntityManager()->createQuery('SELECT count(C.id) as nm FROM ReclamationBundle:Reclamation C WHERE C.statut = :o');
        $query->setParameter(':o','Bug');
        return $query->getResult();
    }

    public function countService()
    {
        $query  = $this->getEntityManager()->createQuery('SELECT count(C.id) as nm FROM ReclamationBundle:Reclamation C WHERE C.statut like :o');
        $query->setParameter(':o','%Service%');
        return $query->getResult();
    }

    public function countOther()
    {
        $query  = $this->getEntityManager()->createQuery('SELECT count(C.id) as nm FROM ReclamationBundle:Reclamation C WHERE C.statut = :o');
        $query->setParameter(':o','Autres');
        return $query->getResult();
    }
    public function countTreated()
    {
        $query  = $this->getEntityManager()->createQuery('SELECT count(C.id) as nm FROM ReclamationBundle:Reclamation C WHERE C.treated = 1');
        return $query->getResult();
    }

    public function countNotTreated()
    {
        $query  = $this->getEntityManager()->createQuery('SELECT count(C.id) as nm FROM ReclamationBundle:Reclamation C WHERE C.treated = 0');
        return $query->getResult();
    }

    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT g
                FROM ReclamationBundle:Reclamation g
                WHERE g.statut LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }
}
