ajouter_infoG:
    path:     /ajout_info
    defaults: { _controller: CvBundle:Default:ajoutInfo }

ajouter_formation:
    path:     /ajout_formation
    defaults: { _controller: CvBundle:Default:ajoutFormation}

ajouter_experience:
    path:     /ajout_experience
    defaults: { _controller: CvBundle:Default:ajoutExperience}

ajouter_competence:
    path:     /ajout_competence
    defaults: { _controller: CvBundle:Default:ajoutCompetence}

ind:
    path:     /indexx
    defaults: { _controller: CvBundle:Default:index }

afficher_info:
    path:     /afficher_info
    defaults: { _controller: CvBundle:Default:afficherInfo }

afficher_formation:
    path:     /afficher_formation
    defaults: { _controller: CvBundle:Default:afficherFormation }

afficher_experience:
    path:     /afficher_experience
    defaults: { _controller: CvBundle:Default:afficherExperience }

afficher_competence:
    path:     /afficher_competence
    defaults: { _controller: CvBundle:Default:afficherCompetence }