<?php

namespace CvBundle\Repository;

/**
 * InfoGRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoGRepository extends \Doctrine\ORM\EntityRepository
{
}
