<?php

namespace CvBundle\Repository;

/**
 * ExperiencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperiencesRepository extends \Doctrine\ORM\EntityRepository
{
    public function order($id)
    {

        $query  = $this->getEntityManager()->createQuery("SELECT C FROM CvBundle:Experiences C WHERE C.user= :id ")
            ->setParameter(':id',$id);
        return $query->getResult();
    }
}
