<?php

namespace CvBundle\Repository;

/**
 * InfoGRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoGRepository extends \Doctrine\ORM\EntityRepository
{
    public function order($id)
    {

        $query  = $this->getEntityManager()->createQuery("SELECT C FROM CvBundle:InfoG C WHERE C.user= :id ")
            ->setParameter(':id',$id);
        return $query->getResult();
    }
}
