<?php

namespace CvBundle\Repository;

/**
 * CertificatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertificatsRepository extends \Doctrine\ORM\EntityRepository
{
}
