<?php

namespace CvBundle\Repository;

/**
 * CompetencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetencesRepository extends \Doctrine\ORM\EntityRepository
{
    public function order($id)
    {

        $query  = $this->getEntityManager()->createQuery("SELECT C FROM CvBundle:Competences C WHERE C.user= :id ")
            ->setParameter(':id',$id);
        return $query->getResult();
    }
}
