<?php

namespace JobpostsBundle\Repository;

/**
 * DemandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeRepository extends \Doctrine\ORM\EntityRepository
{
    function findDemandeDQL($iduserA)
    {
        $query = $this->getEntityManager()
            ->createQuery("select v from JobpostsBundle:Demande v WHERE v.iduserA = :iduserA AND v.etatd = 0 ")
            ->setParameter('iduserA', $iduserA );
        return $query->getResult();


    }

    function findalldemande($idA)
    {
        $query = $this->getEntityManager()
            ->createQuery("delete JobpostsBundle:Demande v WHERE v.ida = :idaa AND v.etatd = 0 ")
            ->setParameter('idaa', $idA );
        return $query->getResult();


    }



    public function findbestd($dated,$datef)
    {
        $query = $this->getEntityManager()->createQuery("SELECT p FROM JobpostsBundle:Demande p WHERE  strtodate(p.datedebutD, '%Y/%m/%d')<= strtodate(:dated, '%Y/%m/%d') AND strtodate(p.datefinD, '%Y/%m/%d') >= strtodate(:datef, '%Y/%m/%d')")
            ->setParameters(array('dated'=> $dated,
                'datef'=>$datef) );

        return $query->getResult();
    }



    public function findbestdd()
    {
        $query = $this->getEntityManager()->createQuery("SELECT p.titre as Subject ,strtodate(p.datedebutD, '%Y/%m/%d') as startHour,strtodate(p.datefinD, '%Y/%m/%d') as endHour FROM JobpostsBundle:Demande p ");


        return $query->getResult();
    }


}
