<?php

namespace BlogBundle\Repository;

/**
 * Commentaire_BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Commentaire_BlogRepository extends \Doctrine\ORM\EntityRepository
{
}
