forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /forum

fix:
    resource: "@FixBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

mgilet_notification:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications