<?php

namespace ForumBundle\Repository;

/**
 * commantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commantRepository extends \Doctrine\ORM\EntityRepository
{
}
