<?php

namespace ForumBundle\Repository;

/**
 * like_qRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class like_qRepository extends \Doctrine\ORM\EntityRepository
{
}
